package com.angryguyy.duels.party;

import org.jetbrains.annotations.Nullable;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * In-memory representation of a persistent party.
 *
 * <p>A party is identified by a numeric id generated by the database
 * and has exactly one leader at any time. Members are stored together
 * with the instant they joined, so that the oldest member can be
 * promoted to leader when the current one leaves.</p>
 *
 * <p>The public flag controls whether the party can be joined by anyone
 * using {@code /party join}. It is kept in memory only; after a server
 * restart every party reverts to private.</p>
 *
 * <p>The instance is mutable and not thread-safe; all mutations must
 * happen on the Bukkit main thread, through {@link PartyManager}.</p>
 */
public class Party {

    /**
     * Hard cap on party size, chosen so that a party split results in
     * two balanced teams of at most ten players each.
     */
    public static final int MAX_MEMBERS = 20;

    private final long id;
    private final Instant createdAt;
    private final Map<UUID, Instant> members;

    private UUID leader;
    private boolean isPublic;

    /**
     * Creates a new party with the given leader as the sole member.
     *
     * @param id        database id
     * @param leader    uuid of the first leader
     * @param createdAt instant the party was created
     */
    public Party(long id, UUID leader, Instant createdAt) {
        this.id = id;
        this.leader = leader;
        this.createdAt = createdAt;
        this.members = new LinkedHashMap<>();
        this.members.put(leader, createdAt);
    }

    /**
     * Returns the database id.
     *
     * @return party id
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the uuid of the current leader.
     *
     * @return leader uuid
     */
    public UUID getLeader() {
        return leader;
    }

    /**
     * Returns the instant the party was created.
     *
     * @return creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns an unmodifiable view of the members, keyed by uuid and
     * sorted by join order.
     *
     * @return member map
     */
    public Map<UUID, Instant> getMembers() {
        return Collections.unmodifiableMap(members);
    }

    /**
     * Returns the current number of members.
     *
     * @return member count
     */
    public int size() {
        return members.size();
    }

    /**
     * Checks whether a player is a member of this party.
     *
     * @param uuid player uuid
     * @return {@code true} if the player belongs to the party
     */
    public boolean isMember(UUID uuid) {
        return members.containsKey(uuid);
    }

    /**
     * Checks whether a player is the current leader.
     *
     * @param uuid player uuid
     * @return {@code true} if the player is the leader
     */
    public boolean isLeader(UUID uuid) {
        return leader.equals(uuid);
    }

    /**
     * Checks whether the party is public (joinable by anyone).
     *
     * @return {@code true} if the party is public
     */
    public boolean isPublic() {
        return isPublic;
    }

    /**
     * Sets the public flag of the party.
     *
     * @param isPublic new value
     */
    public void setPublic(boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * Adds a member to the party.
     *
     * <p>The caller is responsible for enforcing {@link #MAX_MEMBERS}
     * before calling this method.</p>
     *
     * @param uuid     player uuid
     * @param joinedAt instant the player joined
     */
    public void addMember(UUID uuid, Instant joinedAt) {
        members.put(uuid, joinedAt);
    }

    /**
     * Removes a member from the party.
     *
     * <p>If the removed member is the leader and other members remain,
     * the oldest remaining member is promoted automatically. If the
     * removed member is the last one, the party is left in an empty
     * state and the caller should disband it.</p>
     *
     * @param uuid player uuid
     * @return the new leader if a promotion happened, otherwise
     *         {@code null}
     */
    public @Nullable UUID removeMember(UUID uuid) {
        members.remove(uuid);
        if (members.isEmpty()) return null;
        if (!leader.equals(uuid)) return null;
        UUID promoted = getOldestMember();
        if (promoted != null) leader = promoted;
        return promoted;
    }

    /**
     * Returns the oldest member other than the current leader.
     *
     * @return oldest non-leader member uuid, or {@code null} if none
     */
    public @Nullable UUID getOldestMember() {
        UUID oldest = null;
        Instant oldestJoin = null;
        for (Map.Entry<UUID, Instant> entry : members.entrySet()) {
            if (entry.getKey().equals(leader)) continue;
            if (oldestJoin == null || entry.getValue().isBefore(oldestJoin)) {
                oldest = entry.getKey();
                oldestJoin = entry.getValue();
            }
        }
        return oldest;
    }

    /**
     * Forces a new leader.
     *
     * @param uuid uuid of the new leader; must already be a member
     */
    public void setLeader(UUID uuid) {
        if (!members.containsKey(uuid)) {
            throw new IllegalArgumentException("New leader is not a member of the party");
        }
        this.leader = uuid;
    }
}